async (page) => {
  const checks=[];
  const check=(ok,label)=>{if(!ok)throw new Error(label);checks.push(label);};
  await page.setViewportSize({width:390,height:844});
  await page.goto('http://127.0.0.1:4173/?local-preview=1');
  await page.getByRole('button',{name:'🏡 룸',exact:true}).click();
  check(await page.locator('#p6').isVisible(),'룸 탭 연결');
  await page.evaluate(async()=>{if(db!==null)throw new Error('Local preview required');LV=defaultLiving();LV.hearts=1200;await saveLiving();});
  await page.getByRole('button',{name:'🛒 상점',exact:true}).click();
  await page.getByRole('button',{name:'허스키 💗 50',exact:true}).click();
  check(await page.locator('[data-pet-id]').count()===1,'허스키 구매 즉시 거실 등장');
  check(await page.evaluate(()=>LV.hearts===1150),'펫 구매 50하트 차감');
  const before=await page.locator('[data-pet-id]').boundingBox();
  const scene=await page.locator('.living-scene').boundingBox();
  check(before.x>=scene.x&&before.y>=scene.y&&before.x+before.width<=scene.x+scene.width,'애니메이션 펫이 장면 안에 위치');
  await page.getByRole('button',{name:'밥주기 +5💗',exact:true}).click();
  check(await page.evaluate(()=>LV.hearts===1155),'필요한 밥주기 5하트 보상');
  await page.getByRole('button',{name:'밥주기',exact:true}).click();
  check(await page.evaluate(()=>LV.hearts===1155),'연속 밥주기 보상 중복 방지');
  await page.getByRole('button',{name:'공놀이',exact:true}).click();
  check((await page.locator('.pet-family').innerText()).includes('신나게 공을 쫓는 중'),'공놀이 상태 반응');
  await page.getByRole('button',{name:'이름 짓기',exact:true}).click();
  await page.getByLabel('애칭 · 최대 8글자').fill('구름이');
  await page.getByRole('button',{name:'이 이름으로 부르기'}).click();
  await page.getByRole('button',{name:'마당에 보내기',exact:true}).click();
  check(await page.locator('[data-pet-id]').count()===1&&await page.evaluate(()=>locView==='garden'),'펫 마당 이동과 화면 반영');
  await page.reload();
  await page.getByRole('button',{name:'🏡 룸',exact:true}).click();
  await page.getByRole('button',{name:'🌿 텃밭',exact:true}).click();
  check(await page.locator('[data-pet-id]').count()===1&&await page.evaluate(()=>LV.pets[0].nickname==='구름이'),'펫 위치와 애칭 재접속 유지');
  await page.getByRole('button',{name:'1번 밭 씨앗 심기',exact:true}).click();
  await page.getByRole('button',{name:'딸기 10💗',exact:true}).click();
  check(await page.evaluate(()=>LV.garden.plots[0].type==='strawberry'),'고른 씨앗이 심어짐');
  await page.getByRole('button',{name:'1번 밭 딸기 물주기',exact:true}).click();
  check(await page.evaluate(()=>LV.garden.plots[0].stage===1),'첫 물주기 즉시 성장');
  const balance=await page.evaluate(()=>LV.hearts);
  await page.getByRole('button',{name:'1번 밭 딸기 물주기',exact:true}).click();
  check(await page.evaluate(()=>LV.garden.plots[0].stage===1),'물주기 성장 중복 방지');
  check(await page.evaluate(()=>LV.hearts)===balance,'물주기 보상 중복 방지');
  for(let i=0;i<3;i++){
    await page.evaluate(async()=>{LV.garden.plots[0].care=[Date.now()-1];await saveLiving();});
    await page.getByRole('button',{name:'1번 밭 딸기 물주기',exact:true}).click();
  }
  await page.getByRole('button',{name:'1번 밭 딸기 수확하기',exact:true}).click();
  check(await page.evaluate(()=>LV.garden.plots[0]===null&&LV.garden.harvests===1),'네 번 성장 후 수확과 수확 기록');
  await page.getByRole('button',{name:'🛒 상점',exact:true}).click();
  await page.getByRole('button',{name:'구름 펫 침대 💗 40',exact:true}).click();
  await page.getByRole('button',{name:'반짝 물고기 수조 💗 70',exact:true}).click();
  await page.getByRole('button',{name:'튤립 무드등 💗 35',exact:true}).click();
  await page.getByRole('button',{name:'체크 피크닉 세트 💗 55',exact:true}).click();
  await page.getByRole('button',{name:'반딧불 랜턴 💗 40',exact:true}).click();
  await page.getByRole('button',{name:'☕ 크림 소다 카페 💗 200',exact:true}).click();
  const paid=await page.evaluate(()=>LV.hearts);
  await page.getByRole('button',{name:'구름 펫 침대 배치 중 · 보관하기',exact:true}).click();
  await page.getByRole('button',{name:'구름 펫 침대 보유 · 무료 배치',exact:true}).click();
  check(await page.evaluate(()=>LV.hearts)===paid,'보유 소품 보관 및 재배치 무료');
  await page.getByRole('button',{name:'🏠 거실',exact:true}).click();
  await page.getByRole('button',{name:'집에 데려오기',exact:true}).click();
  const old=await page.locator('[data-cinema-title]').innerText();
  await page.getByRole('button',{name:'다음 영화 풍경',exact:true}).click();
  check(await page.locator('[data-cinema-title]').innerText()!==old,'시네마 장면 전환');
  await page.getByRole('button',{name:'시네마 일시정지',exact:true}).click();
  check(await page.locator('[data-cinema-frame]').getAttribute('class')==='cinema-paused','시네마 일시정지');
  await page.getByRole('button',{name:'시네마 재생',exact:true}).click();
  await page.locator('#p6').screenshot({path:'output/playwright/room-mobile.png'});
  await page.getByRole('button',{name:'마당에 보내기',exact:true}).click();
  await page.evaluate(async()=>{LV.garden.plots[0]={type:'strawberry',stage:4,care:[]};LV.garden.plots[1]={type:'tomato',stage:3,care:[Date.now()-1]};LV.garden.plots[2]={type:'grape',stage:2,care:[]};await saveLiving();});
  await page.locator('#p6').screenshot({path:'output/playwright/garden-mobile.png'});
  await page.getByRole('button',{name:'🛒 상점',exact:true}).click();
  await page.locator('#shop-furniture').screenshot({path:'output/playwright/shop-mobile.png'});
  await page.evaluate(async()=>{const original=LV.hearts;LV.hearts=0;await saveLiving();await buyPet('cat','blue');window.insufficientCheck=LV.pets.length===1&&LV.hearts===0;LV.hearts=original;await saveLiving();await buyPet('dog','husky');});
  check(await page.evaluate(()=>window.insufficientCheck&&LV.pets.length===1),'하트 부족 및 중복 펫 구매 거절');
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'390px 가로 넘침 없음');
  return checks;
}
