async (page) => {
  const checks=[];const check=(ok,label)=>{if(!ok)throw new Error(label);checks.push(label);};
  await page.evaluate(()=>{if(db!==null)throw new Error('Local preview required');FT={profiles:{},daily:{}};localStorage.setItem(FORTUNE_KEY,JSON.stringify(FT));renderFortune();});
  await page.getByRole('button',{name:'🔮 운세',exact:true}).click();
  check(await page.locator('#p7').isVisible(),'운세 메뉴 접근');
  check(await page.locator('.compat-tile').count()===6,'6종 궁합 모두 표시');
  check(await page.locator('.score-orb b').innerText()==='—','정보 없으면 점수 만들지 않음');
  await page.locator('.fortune-profile').first().click();
  await page.getByLabel('생년월일',{exact:true}).fill('2024-02-30');
  await page.getByRole('button',{name:'프로필 저장',exact:true}).click();
  check((await page.locator('#fortuneFormError').innerText()).includes('생년월일'),'실재하지 않는 생일 거절');
  await page.getByLabel('생년월일',{exact:true}).fill('1995-06-15');
  await page.getByLabel('MBTI',{exact:true}).selectOption('INFJ');
  await page.getByLabel('혈액형',{exact:true}).selectOption('A');
  await page.getByLabel('성별',{exact:true}).selectOption('남성');
  await page.locator('#fortuneForm summary').click();
  await page.getByLabel('연주',{exact:true}).fill('갑자');
  await page.getByLabel('월주',{exact:true}).fill('병인');
  await page.getByLabel('일주',{exact:true}).fill('갑축');
  await page.getByRole('button',{name:'프로필 저장',exact:true}).click();
  check((await page.locator('#fortuneFormError').innerText()).includes('유효한 간지'),'불가능한 간지 조합 거절');
  await page.getByLabel('일주',{exact:true}).fill('무진');
  await page.getByRole('button',{name:'프로필 저장',exact:true}).click();
  check(!(await page.locator('#azitDialog').isVisible()),'첫 프로필 저장');
  await page.locator('.fortune-profile').nth(1).click();
  await page.getByLabel('생일 기준',{exact:true}).selectOption('lunar');
  await page.getByLabel('생년월일',{exact:true}).fill('2017-03-01');
  await page.getByLabel('음력 윤달',{exact:true}).check();
  await page.getByRole('button',{name:'프로필 저장',exact:true}).click();
  check((await page.locator('#fortuneFormError').innerText()).includes('윤달'),'존재하지 않는 윤달 거절');
  await page.getByLabel('생년월일',{exact:true}).fill('2017-05-01');
  await page.getByLabel('MBTI',{exact:true}).selectOption('ENFP');
  await page.getByLabel('혈액형',{exact:true}).selectOption('B');
  await page.getByLabel('성별',{exact:true}).selectOption('여성');
  await page.getByLabel('태어난 시각을 몰라요',{exact:true}).uncheck();
  await page.getByLabel('태어난 시각',{exact:true}).fill('14:30');
  await page.locator('#fortuneForm summary').click();
  await page.getByLabel('연주',{exact:true}).fill('丁酉');
  await page.getByLabel('월주',{exact:true}).fill('丙午');
  await page.getByLabel('일주',{exact:true}).fill('壬午');
  await page.getByLabel('시주',{exact:true}).fill('丁未');
  await page.getByRole('button',{name:'프로필 저장',exact:true}).click();
  check(await page.evaluate(()=>birthFacts(FT.profiles[2]).solarDate==='2017-06-24'),'한국 윤달 → 양력 변환 기준 사례');
  check(await page.evaluate(()=>compatResults().filter(r=>r.score!==null).length===5),'두 프로필 입력 후 5개 궁합 계산');
  check(await page.evaluate(()=>{const original=FT.profiles;const before=compatResults().map(r=>r.score).join(',');FT.profiles={1:original[2],2:original[1]};const after=compatResults().map(r=>r.score).join(',');FT.profiles=original;return before===after;}),'궁합 점수는 두 사람 순서와 무관');
  await page.locator('#p7').screenshot({path:'output/playwright/fortune-mobile.png'});
  await page.getByRole('button',{name:'오늘 운세',exact:true}).click();
  await page.locator('.daily-seal').first().click();
  await page.locator('.daily-seal').first().click();
  const daily=await page.locator('.daily-luck').first().innerText();
  await page.reload();
  await page.getByRole('button',{name:'🔮 운세',exact:true}).click();
  await page.getByRole('button',{name:'오늘 운세',exact:true}).click();
  check(await page.locator('.daily-luck').first().innerText()===daily,'새로고침 후 같은 일일 운세');
  await page.locator('#p7').screenshot({path:'output/playwright/daily-mobile.png'});
  await page.getByRole('button',{name:'타로 한 장',exact:true}).click();
  await page.getByRole('button',{name:'2번째 타로 카드 뽑기',exact:true}).click();
  const draw=await page.evaluate(()=>JSON.stringify(todayFortune(1).tarot));
  await page.evaluate(()=>drawTarot(2));
  check(await page.evaluate(()=>JSON.stringify(todayFortune(1).tarot))===draw,'같은 날 타로 재추첨 방지');
  await page.getByRole('button',{name:'너',exact:true}).click();
  await page.getByRole('button',{name:'1번째 타로 카드 뽑기',exact:true}).click();
  check(await page.evaluate(()=>compatResults().find(r=>r.id==='tarot').score!==null),'두 사람 뽑기 후 타로 궁합');
  await page.locator('#p7').screenshot({path:'output/playwright/tarot-mobile.png'});
  await page.reload();
  check(await page.evaluate(()=>JSON.stringify(todayFortune(1).tarot))===draw,'재접속 후 뽑은 카드 유지');
  check(await page.evaluate(()=>Object.keys(FT.profiles).length===2),'운세 프로필 재접속 유지');
  check(await page.evaluate(()=>{
    const f=s=>birthFacts({birth:s,calendar:'solar'});
    return f('2024-02-09').animal===3&&f('2024-02-10').animal===4&&f('2024-01-19').star.n==='염소자리'&&f('2024-01-20').star.n==='물병자리'&&f('2024-02-29')!==null&&f('2023-02-29')===null;
  }),'설 전후 띠·별자리 경계·양력 윤년');
  check(await page.evaluate(()=>koreaDay(new Date('2026-09-05T14:59:59Z'))==='2026-09-05'&&koreaDay(new Date('2026-09-05T15:00:00Z'))==='2026-09-06'),'한국 시간 자정 날짜 전환');
  await page.getByRole('button',{name:'🔮 운세',exact:true}).click();
  for(const width of [320,375,390,768,1440]){
    await page.setViewportSize({width,height:900});
    check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'가로 넘침 없음 '+width+'px');
  }
  await page.setViewportSize({width:390,height:844});
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.getByRole('button',{name:'🏡 룸',exact:true}).click();
  check(await page.evaluate(()=>{const el=document.querySelector('.pet-roam');return !el||getComputedStyle(el).animationName==='none';}),'동작 줄이기 설정 존중');
  await page.emulateMedia({reducedMotion:'no-preference'});
  return checks;
}
